function createfigure(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of loglog x data
%  YMATRIX1:  matrix of loglog y data
%  X2:  vector of loglog x data
%  YMATRIX2:  matrix of loglog y data

%  Auto-generated by MATLAB on 23-Apr-2025 21:58:19

% Create figure
figure('OuterPosition',[-971 -117.4 703.2 916]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple line objects using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'LineWidth',2);
set(loglog1(1),'DisplayName','X axis',...
    'Color',[0.0745098039215686 0.623529411764706 1]);
set(loglog1(2),'DisplayName','Y axis',...
    'Color',[1 0.411764705882353 0.16078431372549]);
set(loglog1(3),'DisplayName','Z axis',...
    'Color',[0.392156862745098 0.831372549019608 0.0745098039215686]);

% Create multiple line objects using matrix input to loglog
loglog2 = loglog(X2,YMatrix2,'LineWidth',1,'Color',[0 0 0]);
set(loglog2(1),'DisplayName','Target');
set(loglog2(2),'DisplayName','-3 dB','LineStyle','-.');
set(loglog2(3),'DisplayName','+6 dB','LineStyle','--');

% Create zlabel
zlabel('ZLabel');

% Create ylabel
ylabel({'Peak Acceleration (g)'},'HorizontalAlignment','center');

% Create xlabel
xlabel({'Frequency (Hz)'},'HorizontalAlignment','center');

% Create title
title('Acceleration Shock Response Spectrum Q=10',...
    'HorizontalAlignment','center',...
    'FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[100 10000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1 10000]);
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'GridLineStyle',':','MinorGridLineStyle','--','XMinorTick','on',...
    'XScale','log','YMinorTick','on','YScale','log');
% Create legend
legend(axes1,'show');

